### ISSUE TITLE
Problem downloading

### ISSUE THREAD

**Issue by arzaz** [techdealer/plugin.audio.musicbox#14]
![xbmc log](https://cloud.githubusercontent.com/assets/9026875/4682506/affd89ba-561d-11e4-915e-78a9d67e3c64.png)
Dear techdealer,
Please find attached log file
Regards

After several attempts i noticed that all artist names with high and low tones (é, è....) give me error Music box script?
May be it's the reason that i cannot download any songs or albums?

**Comment by romanoh** [comment]
I have an android OUYA, and also the folder is created, it says ok, but nothing is transferred, i have a nas.
