### ISSUE TITLE
spotify and deezer

### ISSUE THREAD

**Issue by nickshe89** [techdealer/plugin.audio.musicbox#18]
i got spotify charts can you add it 
http://charts.spotify.com/?object=tracks&rank=most_streamed&country=global&windowtype=weekly&date=latest

http://www.deezer.com/tops/track

**Comment by nickshe89** [comment]
u want add it

**Comment by nickshe89** [comment]
can you add http://api.tunigo.com/v3/space/toplists?region=
http://api.tunigo.com/v3/space/featured-playlists?region=
http://api.tunigo.com/v3/space/genres?region=

thanks

**Comment by techdealer** [comment]
I added Deezer and Traxsource in the commit 7b6250aa57c310e169c8c09c2bf45cf1bc291ae6

Spotify charts were descontinued as well as spotify apps. As Tunigo was an app for spotify, probably will also be descontinued or reformuled so I will not add for now.
