### ISSUE TITLE
Music box download 

### ISSUE THREAD

**Issue by adampriest1606** [techdealer/plugin.audio.musicbox#20]
Hi, am having big trouble downloading music from this addon I was downloading a album fine the all of a sudden got a script error and is stuck on preparing to download, many thanks on any help resolving this

**Comment by techdealer** [comment]
Hello,

In some cases that the download fail, is necessary to delete the file commoncache.db, for simpledownloader work properly again. You tried to do this?

**Comment by adampriest1606** [comment]
Where and how would I delete this?

Thanka

**Comment by techdealer** [comment]
The location of that file depends on the operating system used. That file should be stored somewhere under the userdata directory.

**Comment by adampriest1606** [comment]
am using rasbrrry pi2, do I delete it on the pi or do I have to do it on laptop sorry am not that good with the under the bonnet technicals, thanks

**Comment by techdealer** [comment]
You have to do it on laptop. I am not sure about the exact file location on pi.

**Comment by richard053** [comment]
Hello techdealer,

I found and deleted The commoncache.db file, but still not able to download any album.
Script error still appears on my xbmc.
I'm running xbmc on a Rasberry pi 2 with openelec 5.06.

Can you please fix it ? ITS à super plug-in and The only thing missing is The download option.

Greetings and keep Up The good work.

Richard

**Comment by rpuls** [comment]
Hi, im having same problem. downloaded the first 8-10 tracks without problems, then i got this error. Tried changing the download directory, and restart the pi (im also using raspberry pi) OSMC

**Comment by techdealer** [comment]
@rpuls try to delete the commoncache.db file.

**Comment by rpuls** [comment]
Where do i locate that file?

**Comment by mattmayatt** [comment]
Hi techdealer , I'm having trouble downloading albums , music box downloads the first song then get an error on the second..
Happens on any album.
I'm using Android and I deleted the commoncache.db file.
Cheers for any information, fantastic add-on by the way :)

**Comment by mattmayatt** [comment]
I'm using the latest version from the repo.

**Comment by mattmayatt** [comment]
Downloads to internal memory on my shield TV but not to my nas , doesn't download to anything on my phone.

**Comment by phillyjeff** [comment]
Ugh. Having the same issue. Was able to download for a few days, now not able to download anymore. I looked and I dont have a commoncache.db file

**Comment by Gee-Bee** [comment]
I can confirm that deleting commoncache.db works in most cases.
On android it located in `_path-to-sd-card_/Android/Android/data/org.xbmc.kodi/files/.kodi/temp`

However, there's problem when song name contains non ASCII characters. From logs:
`UnicodeEncodeError: 'ascii; codec can't encode character u'\xeb' in position 113: ordinal not in range(128)`

**Comment by kgd4170** [comment]
I checked my SD card as suggested by Gee-Bee but nothing there, problem still exists, any further advice?

**Comment by GitHubRandy** [comment]
I am using Kodi & Music Box on a MacBook Pro.  Had the same problems as others.  Deleted commoncache.db and restarted Kodi.  Now all works fine.  File is located in Temp folder:
Mac HD/Users/"Your User Name"/.kodi/temp

Thanks sooooo much.

**Comment by phillyjeff** [comment]
Everything is broken with downloads again. Both Windows and Mac can no longer downloaded. I deleted the commoncache.db file but still broken
