### ISSUE TITLE
Can't launch: "Captcha needed" despite "Looged in successfully" msg.

### ISSUE THREAD

**Issue by fonsecas72** [techdealer/plugin.audio.musicbox#24]
Hi,
I wanted to try out this add-on but I'm getting a "Captcha needed" error when launching.

I've fill in the credentials of vk.com and last.fm and even tried to change the source to youtube but nothing seems to work. Can you help me out?

**Comment by techdealer** [comment]
Check the latest version from git. Replace the `addon.py` and `vkAuth.py` with the latest version from here.

**Comment by fonsecas72** [comment]
@techdealer I've downloaded and updated these files at ~/.kodi/addons/plugin.audio.musicbox but it doesn't seem to work neither. Is this the right directory? 
If you need any extra information please ask. Thanks.
