### ISSUE TITLE
favourites

### ISSUE THREAD

**Issue by dexyweescot** [techdealer/plugin.audio.musicbox#26]
Can you tell me where the favourites are stored and if i can back them up for any updates coming out?

I have it installed on Kodi on windows 7

**Comment by techdealer** [comment]
The favourites are stored in `\userdata\addon_data\plugin.audio.musicbox`, in a file called `favorites.json`

In the case of the windows7, the full path is:

`C:\Users\USERNAME\AppData\Roaming\Kodi\userdata\addon_data\plugin.audio.musicbox`

**Comment by dexyweescot** [comment]
Thank you. Perfect 👍🏻

Regards
DG
