### ISSUE TITLE
Addon not working at all

### ISSUE THREAD

**Issue by JacobSP2** [techdealer/plugin.audio.musicbox#28]
When installed this addon, and opened it, a blank dialog box appears, and when click ok, another one with "This addon cant be configured". So it is completely useless, tried installing in
-Android
-Raspberry Pi OSMC
-Windows
And no one works
Please help and fix this error.
Thanks in advance

**Comment by techdealer** [comment]
Currently there is a problem with the repository. However, the addon is working correctly.

Try to install the standalone attached version from zip file:
[plugin.audio.musicbox-0.1.2.zip](https://github.com/techdealer/plugin.audio.musicbox/files/63407/plugin.audio.musicbox-0.1.2.zip)
