### ISSUE TITLE
Failing VK authentication

### ISSUE THREAD

**Issue by thwaller** [techdealer/plugin.audio.musicbox#31]
Music Box is failing VK authentication on both the regular user and password combo and the application specific password option. All I get is invalid user / pass. The information being used is correct, other Kodi plugin works fine as do all my other apps for VK. Based on me getting a text on login attempt, I guess maybe this is due to the 2 factor authentication?

**Comment by techdealer** [comment]
The 2 factor authentication was added today in commit 543fa8e5a4d61030edab7a55a6199af5dfba1765. Hope it helps you.

**Comment by kowalmisiek** [comment]
Hello. I have new instalation windows 10 and kodi 17. After installing musicbox I logon failure to vk.com. The login and password are correct. During the installation, I had error "common plugin cache." I installed a few times and continues to be a mistake. Any ideas?

Error: Failed vk.com authentication 

I do not understand what's going on? On another computer the musicbox works fine. Same as windows 10 and kodi 17.

On my HTPC the plugin does not work
I would send logs but I do not know what?
