### ISSUE TITLE
Kodi TvOs

### ISSUE THREAD

**Issue by pedrofscaetano** [techdealer/plugin.audio.musicbox#32]
Hello, i can't connect to my Vk account on my kodi on TVOs! I think the problem is on Addon! Becouse i can log in in my computer!

**Comment by techdealer** [comment]
Are you using the latest version (0.1.3)?
What error message the addon returns?
Do you have any log?

**Comment by pedrofscaetano** [comment]
Yes, v 0.1.3. 
The error is that it always saying "autentication failed", but on my PC-Windows i put the same user and pass and it works.

I think that the addon isn't prepared for kodi on tvios! 
Probably you need to check it and updated it!
Or do you have any tipp?
Thanks

**Comment by pedrofscaetano** [comment]
The problema is the compatibility with Pyton! You need to Update the addon!
