### ISSUE TITLE
Music Box stopped downloading, get error message

### ISSUE THREAD

**Issue by teddawson** [techdealer/plugin.audio.musicbox#36]
Hi, am having big trouble downloading music from this addon I was downloading a album fine the all of a sudden got a script error and is stuck on preparing to download, many thanks on any help resolving this

**Comment by TheHashasin** [comment]
If it sticks after several methods I found this worked on Kodi Jarvis 16.0
Delete the plugin, clear Kodi Cache, Clear any Packages, force close Kodi. Go to Apps, select Kodi and Select Stop! Clear Kodi Cache and do a hard system reset. Ree boot enter Kodi and run the zip file for MB, start Music Box.

Android 4.4

**Comment by phillyjeff** [comment]
Yeah downloads are broken again. Deleting the cache sometimes fixes the problem, other times it doesnt, I've uninstalled, upgraded, downgraded Kodi. Still broken
