### ISSUE TITLE
Music Box verson for Kodi Helix 14.0

### ISSUE THREAD

**Issue by axelmunich** [techdealer/plugin.audio.musicbox#37]
Hello,

which version of the addon is working with the Helix 14.0? Where can I find it?

Thank you very much in advanced.

**Comment by dexyweescot** [comment]
I thot it had all shut down?

**Comment by axelmunich** [comment]
I'm using Kodi Helix on my Raspberry Pi as media center... Still working well.. Also with new addon as Exodus.. 

But when I try to install Music Box I receive the msg No dependencies met :(

**Comment by techdealer** [comment]
Minimum required version is 15.X Update your system if you want to use the addon.
