### ISSUE TITLE
Randomize liked from Last.fm

### ISSUE THREAD

**Issue by john3voltas** [techdealer/plugin.audio.musicbox#39]
Hi techdealer.
As you know, last.fm allows to scrobble and to like songs.
One can always list his own songs already scrobbled and also the ones that he marked as liked.
Would it be possible to listen only the tracks that I have already tagged as liked songs?
If so, would it also be possible for musicbox to randomize that liked list so that I could hear the songs that I like but not on the same sorting sequence that I heard them before?
The main idea would be for instance to add 1000 songs to the liked songs list and then have musicbox choose only 50 in random and in a random sort.
Thanks for this excellent Kodi addon and for sharing it with us. :-)

**Comment by techdealer** [comment]
Hello,

By "liked songs" you mean "loved songs" at last.fm, right?
It's already possible to listen last.fm "loved" songs in Music Box. This function is available in "User Space" > "My last.fm - loved tracks".
The order of the songs (in the pages) in that mode follows the order returned by the last.fm API.  However, you can randomize the playlist order by pressing the "Shuffle" button in Kodi player.
The number of songs per page is also customizable in addon settings (between 10 and 50).

I will study the implementation of a "shuffle mode" with the data from last.fm (scrobble and loved tracks) in a future version. Thanks for the sugestion.

**Comment by john3voltas** [comment]
Thanks for your reply, techdealer.
Just to clarify, if I choose to get 10 songs per page and my last 10 songs "loved" on last.fm were song 1, song 2...until song 10, does that mean that using the "User Space" > "My last.fm - loved tracks" I will always get a exactly those 10 songs in which they may or may not be in that order, right? I mean, it won't ever show me song 11 or song 12 on the first 10 hits, right?
Because that's what I was looking for. I was looking for a way that it would look at *all* my loved songs and then randomize their sort sequence and then give me something like:
song 28
song 992
song 317
etc
Do you think there's a way to achieve that? Thanks in advance.

**Comment by techdealer** [comment]
Yes, that's it. If you set 10 songs per page, using the "User Space" > "My last.fm - loved tracks" you will have these 10 songs listed in the same order as returned from the last.fm API. Using player shuffle mode you can randomize the order in which these 10 songs play.
It's not what you want, but it's the closest you can do with the current version.

As I said before, I will study the implementation of this suggestion in a future version.

**Comment by john3voltas** [comment]
Thanks for clarifying it, techdealer.
Hoping to hear about an implementation of my suggestion in the future.
Thanks
