### ISSUE TITLE
russian voice when trying to play tracks

### ISSUE THREAD

**Issue by cfdcoste** [techdealer/plugin.audio.musicbox#41]
Hi, I am in Music Box add on KODI/osmc on my rpi. Logged in succesfully but when I try to play a song I hear someone speaking russian (mentioning android and ios ...). What do I need to do ?

**Comment by ferflux** [comment]
Same issue, unable to play any song, always 25 seconds of the russian voice when I try it, both in android and windows. I just installed it and I don't know if there is any configuration that I have overlooked...

**Comment by techdealer** [comment]
Looks like that the VK Public API for Audio was discontinued. More info [here](https://vk.com/dev/audio_api).

As a temporary solution, you can use Youtube as source (Addon Settings > General > Media Source).

**Comment by igotu2** [comment]
So does that mean that this add on will no longer work or get updates since they discontinued the API can't the end user add there own API

**Comment by techdealer** [comment]
A new version of the addon should be released soon. Stay tuned!
