### ISSUE TITLE
8traks issue

### ISSUE THREAD

**Issue by lollo78** [techdealer/plugin.audio.musicbox#42]
Hi, I'm unable to play 8traks contents also after log with my free account.
Log here
http://sprunge.us/fSVJ

Thx for this great addon

**Comment by techdealer** [comment]
It looks like 8tracks has added geographic restrictions regarding the use of api. The requests return the following error:
> Due to international streaming restrictions, this playlist may have limited playback in your region.

After a google search I found the following post (in 8tracks official blog):
[A change in our international streaming - 8tracks blog](https://blog.8tracks.com/2016/02/12/a-change-in-our-international-streaming/)

According to it 8tracks will only be available in the **USA** and **Canada**.
The 8tracks functions should be working for users in these 2 countries. I do not think it's possible to correct the problem for other users. At most, I can put a warning to inform users about the new limitations.

Thanks for the report.  😃

**Comment by lollo78** [comment]
Thx for the replay. What a pity.
Could you add a switch into the add-on settings to disable 8tracks and leave a more cleaned interface for the users like me that doesn't live in USA or Canada.
Thx a lot

**Comment by techdealer** [comment]
As suggested, I added an option to hide 8tracks in commit ddb97551c69837e99666c32735fa3c742437ab9d.
It is already available in the latest version of the addon (0.1.5).

I have no plans to add proxy/VPN support in addon.
