### ISSUE TITLE
vk resolver

### ISSUE THREAD

**Issue by arzaz** [techdealer/plugin.audio.musicbox#43]
After first installation all was working well, but now at every time i try to play a music i got error "script musicbox failed!"
For info i got the same error on Android & ios box

**Comment by techdealer** [comment]
Try deleting the cookie file, located in Kodi AppData folder:

`Kodi (AppData folder) > addon_data > plugin.audio.musicbox > cookies.txt`

After, reopen the addon to reauth again.

**Comment by arzaz** [comment]
Many thanks techdealer

**Comment by techdealer** [comment]
I added an aditional check for expired cookies in commit 0da0bec0de4e68f8de8205911796adf872eda99e.
It is already available in the latest version of the addon (0.1.5).

Hopefully, the problem should not happen again. Thanks for the report. 😃

**Comment by arzaz** [comment]
Dear techdealer

Sorry to inform you that the problem happened again "Error musicbox" with the latest version 0.1.5

Please your help

**Comment by techdealer** [comment]
I added an additional checker in commit 288a41201c019022601ea9cc60dd5c50859606a4 [Reauth again when vk.com resolvers fail].

Please test the new released version v0.1.6.

**Comment by arzaz** [comment]
All is in order now

Many thanks again techdealer
