### ISSUE TITLE
Vk no more music?

### ISSUE THREAD

**Issue by lollo78** [techdealer/plugin.audio.musicbox#46]
Hi, trying to play a content with VK, instead of the music I hear a vocal message in russian.
I don't understand Russian, but seems that music is now blocked (seems that it speaks about Android app).
O_o
This is the end or you could bypass it with some magic like an user agent header?

**Comment by techdealer** [comment]
New version v0.1.7 released today. The addon is "rocking" again!

Thanks for the report. 😃

**Comment by lollo78** [comment]
Thanks a lot ;)
