### ISSUE TITLE
Techdealer repo?

### ISSUE THREAD

**Issue by ijm8710** [techdealer/plugin.audio.musicbox#48]
Thanks for your work it's great. Wanted to
Update music box as I saw you updated it. How do I do so? Unlike most addons which I install through a repo, I installed from the zip. But the zip on github seems to be 1.3 which is outdated. Also I'd like to have the repo in general so I can keep your excellent app up to date. Thanks

**Comment by ijm8710** [comment]
Actually sorry I think I was mixing up v1.3 of the repo and v0.1.8 of the addon itself. It's weird because most sites that guide how to install addons thru repos are thru a website you add while this I had to sideloade the zipfile to add the repo

**Comment by ijm8710** [comment]
Two other questions since I have this open

1. Occasionally it gives me a log error when searching..generaly I have to play a song from the top charts when the app starts up before searching for something specific
2) anyway to view play history?

**Comment by techdealer** [comment]
1. It seems that what-song has been experiencing some technical problems. I corrected this in a new version (v0.1.9) released a few minutes ago.

2.Yes, there is a way. You need to install and configure Last.FM Scrobbler (service.scrobbler.lastfm) addon.
All scrobbed music's will appear in MusicBox > UserSpace.
Please note that you will need a last.fm account.

**Comment by ijm8710** [comment]
Excellent! Thanks
