### ISSUE TITLE
Error: Failed Vk.com authentication

### ISSUE THREAD

**Issue by arzaz** [techdealer/plugin.audio.musicbox#50]
Dear Techdealer

Please your help

**Comment by jamesvulcan** [comment]
Hi Techdealer
I have the same problem with failed Vk authentication. I use kodi 16.1 and 17 on two different Mac computers. Suddenly, I can't log in with Musicbox on both computers.
Maybe it's the problem is the two step authentication? Or website changes?

**Comment by HighTech1972** [comment]
Same problem here

**Comment by techdealer** [comment]
New version 0.2.1 released today. It is available in my repository.
Hopefully the problem is solved.

Thanks for the report.

**Comment by arzaz** [comment]
Dear Techdealer,
Only version 0.2.0 is available in your repository.
Please your help.

**Comment by HighTech1972** [comment]
Same here

**Comment by jamesvulcan** [comment]
Dear Techdealer.

Thanks for the update. 0.2.1 is working for mac on Jarvis 16.1 and 17.
Problem is solved.
I found it on the techdealer repo.

Thank you!

**Comment by techdealer** [comment]
@arzaz and @HighTech1972 try to force "Check For Updates" in the repo.
