### ISSUE TITLE
Musicbox not connecting to music source

### ISSUE THREAD

**Issue by jamesvulcan** [techdealer/plugin.audio.musicbox#52]
Dear Techdealer.

The musicbox plugin stopped working today for Kodi 16.1 and Kodi 17.
Password and Authentication are working but not connecting to music.
First, it played an announcement in Russian saying something about Android users when I tried to play something. Now, it doesn't find any music.
Sorry to bother you.
Thanks for your hard work.

**Comment by Gcvanasel** [comment]
Hi,

I get the same Russian voice. Please advise

**Comment by Durutti23** [comment]
This app is broken.
Me too! I only hear a Russian voice.
What should I do?

**Comment by jamesvulcan** [comment]
Dear Techdealer.

Today, Musicbox is working on my iPad using Kodi 16.1.
It started working after I updated the Sportdevil addon.
However, I updated my Kodi 16. and 17 for mac and MusicBox still doesn't work.
Mystery......
Any suggestions on what I should do?
sorry to bother you.
Thanks

**Comment by jamesvulcan** [comment]
Update
Its working on all devices now but it plays only one track and can't find next track.
I must close addon and turn on again to play next track.
strange.

**Comment by jamesvulcan** [comment]
Dear Techdealer.

The Musicbox app seems to be broken again.
Or maybe the website it connects to is broken?
Any suggestions?
